#!/bin/bash

echo "=== How to Deploy Cloudflare Custom WAF Rule ==="
echo ""

echo "STEP 1: DEPLOY THE RULE"
echo "======================="
echo ""
echo "In your Cloudflare dashboard:"
echo "1. Go to Security > WAF > Custom Rules"
echo "2. Find your 'API Bypass for Legal Subdomain' rule"
echo "3. Look for the rule status - it should show 'Draft' or 'Disabled'"
echo "4. Click the toggle switch next to the rule to ENABLE it"
echo "5. The status should change to 'Enabled' or 'Active'"
echo ""

echo "STEP 2: VERIFY RULE IS ACTIVE"
echo "============================="
echo ""
echo "Check the rule shows:"
echo "- Status: Enabled/Active"
echo "- Expression: (http.host eq \"legal.albpetrol.al\" and http.request.uri.path contains \"/api/\")"
echo "- Action: Skip"
echo ""

echo "STEP 3: RULE PROPAGATION"
echo "========================"
echo ""
echo "- Cloudflare rules typically take 1-3 minutes to propagate globally"
echo "- Wait 2-3 minutes after enabling before testing"
echo ""

echo "STEP 4: TEST THE LOGIN"
echo "======================"
echo ""
echo "After 2-3 minutes, test the login:"
echo "1. Go to https://legal.albpetrol.al"
echo "2. Try logging in with: it.system@albpetrol.al"
echo "3. Use your password"
echo ""
echo "Expected result: Login should work without JSON parsing errors"
echo ""

echo "STEP 5: IF STILL NOT WORKING"
echo "============================"
echo ""
echo "If login still fails:"
echo "1. Check rule priority - move it to the TOP of custom rules list"
echo "2. Verify the expression syntax is exactly correct"
echo "3. Try temporarily setting Security Level to 'Essentially Off' for the subdomain"
echo "4. Check if there are other WAF rules that might be conflicting"
echo ""

echo "ALTERNATIVE: PAGE RULE METHOD"
echo "============================="
echo ""
echo "If WAF custom rules don't work, try Page Rules:"
echo "1. Go to Rules > Page Rules"
echo "2. Create rule: legal.albpetrol.al/api/*"
echo "3. Set: Security Level = Essentially Off"
echo "4. Set: Cache Level = Bypass" 
echo "5. Save and make sure it's at the TOP of page rules list"
echo ""

echo "The key is making sure the rule is ENABLED and at high priority!"
echo ""