#!/bin/bash

# Fix Cloudflare Tunnel API Blocking Issue for legal.albpetrol.al
# Tunnel ID: c51774f0-433f-40c0-a0b6-b7d3145fd95f

echo "=== Cloudflare Tunnel API Fix for legal.albpetrol.al ==="
echo ""

echo "TUNNEL CONFIGURATION DETECTED:"
echo "- Domain: legal.albpetrol.al"
echo "- Tunnel: c51774f0-433f-40c0-a0b6-b7d3145fd95f.cfargotunnel.com"
echo "- Type: CNAME (Proxied)"
echo ""

echo "ISSUE: Cloudflare WAF is challenging API requests through the tunnel"
echo "SOLUTION: Configure Cloudflare rules specifically for your subdomain"
echo ""

echo "STEP 1: CLOUDFLARE DASHBOARD CONFIGURATION"
echo "========================================="
echo ""
echo "1. Login to Cloudflare Dashboard"
echo "2. Select the 'albpetrol.al' domain (parent domain)"
echo "3. Navigate to Security > WAF > Custom Rules"
echo "4. Create a new Custom Rule:"
echo ""
echo "   Rule Name: API Bypass for Legal Subdomain"
echo "   Expression: (http.host eq \"legal.albpetrol.al\" and http.request.uri.path contains \"/api/\")"
echo "   Action: Skip"
echo "   Skip options: Select ALL of the following:"
echo "   - All remaining custom rules"
echo "   - Managed Rulesets"  
echo "   - Rate Limiting rules"
echo "   - Bot Fight Mode"
echo "   - Super Bot Fight Mode"
echo ""
echo "5. Save and Deploy the rule"
echo ""

echo "STEP 2: ALTERNATIVE - PAGE RULES (if WAF Custom Rules not available)"
echo "================================================================="
echo ""
echo "1. Go to Cloudflare Dashboard > Rules > Page Rules"
echo "2. Create new Page Rule:"
echo ""
echo "   URL Pattern: legal.albpetrol.al/api/*"
echo "   Settings:"
echo "   - Security Level: Essentially Off"
echo "   - Browser Integrity Check: Off"
echo "   - Challenge Passage: 30 minutes"
echo "   - Cache Level: Bypass"
echo ""
echo "3. Order: Make sure this rule is at the top of your Page Rules list"
echo "4. Save and activate"
echo ""

echo "STEP 3: VERIFY TUNNEL AND SERVER STATUS"
echo "======================================="

# Check if we can test locally (this won't work from Replit, but shows what to check)
echo "Commands to run on your production server (10.5.20.31):"
echo ""
echo "# Check tunnel status"
echo "sudo systemctl status cloudflared"
echo ""
echo "# Check application status"
echo "sudo systemctl status albpetrol-legal"
echo ""
echo "# Check nginx status" 
echo "sudo systemctl status nginx"
echo ""
echo "# Test local API endpoint"
echo "curl -X POST http://localhost:5000/api/auth/login \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"email\":\"it.system@albpetrol.al\",\"password\":\"[password]\"}'"
echo ""

echo "STEP 4: TUNNEL-SPECIFIC CONSIDERATIONS"
echo "====================================="
echo ""
echo "Since you're using Cloudflare Tunnel:"
echo "- The tunnel acts as a secure connection from your server to Cloudflare"
echo "- All security policies are applied at the Cloudflare edge"
echo "- Your origin server (10.5.20.31:5000) doesn't need to handle HTTPS directly"
echo "- The tunnel config should route /api/* paths correctly"
echo ""

echo "STEP 5: TEST AFTER IMPLEMENTING RULES"
echo "===================================="
echo ""
echo "Test with a browser or curl:"
echo "curl -X POST https://legal.albpetrol.al/api/auth/login \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -H 'User-Agent: Mozilla/5.0 (compatible)' \\"
echo "     -d '{\"email\":\"it.system@albpetrol.al\",\"password\":\"[password]\"}'"
echo ""
echo "Expected result: JSON response instead of HTML challenge page"
echo ""

echo "TROUBLESHOOTING: If still blocked after rules"
echo "============================================="
echo ""
echo "1. Check rule order - API bypass rules should be first priority"
echo "2. Verify the tunnel configuration includes API path routing"
echo "3. Check if Bot Fight Mode is enabled at account level"
echo "4. Consider whitelisting your client IP temporarily for testing"
echo ""

echo "PRIORITY: Implement STEP 1 (Custom WAF Rule) first - this should resolve the login issue."
echo ""